/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function TmBs(props) {
  const group = useRef();
  const blueSphere = React.createRef("blueSphere");
  const { nodes, materials } = useGLTF(
    process.env.PUBLIC_URL + "/tmBs.gltf"
  );
 // const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null} name="BlueTopGroup">
      <group name="Scene">
        <group name="ConeBlue" rotation={[0, Math.PI / 4, 0]}>
          <mesh
            name="ConeBlue_1"
            geometry={nodes.ConeBlue_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="ConeBlue_2"
            geometry={nodes.ConeBlue_2.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="ConeBlue_3"
            geometry={nodes.ConeBlue_3.geometry}
            material={materials["Material.003"]}
          />
          <mesh ref={blueSphere}>
            <sphereBufferGeometry args={[0.01, 24, 24]} />
            <meshStandardMaterial color={"blue"} />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(process.env.PUBLIC_URL + "/tmBs.gltf");
