/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function TmGs(props) {
  const group = useRef();
  const greenSphere = useRef();
  const { nodes, materials } = useGLTF(
    process.env.PUBLIC_URL + "/tmGs.gltf"
  );
  //const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="ConeGreen" rotation={[0, Math.PI / 4, 0]}>
          <mesh
            name="ConeGreen_1"
            geometry={nodes.ConeGreen_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="ConeGreen_2"
            geometry={nodes.ConeGreen_2.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="ConeGreen_3"
            geometry={nodes.ConeGreen_3.geometry}
            material={materials["Material.004"]}
          />
          <mesh ref={greenSphere}>
            <sphereBufferGeometry args={[0.01, 24, 24]} />
            <meshStandardMaterial color={"green"} />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(process.env.PUBLIC_URL + "/tmGs.gltf");
